/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PROTO_FILES_MESSAGES_PB_H_INCLUDED
#define PB_PROTO_FILES_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Message3_StationType { 
    Message3_StationType_ESP = 0, 
    Message3_StationType_RASPBERRY = 1 
} Message3_StationType;

/* Struct definitions */
typedef struct _Message1_Station { 
    char name[128]; 
    int32_t id; 
} Message1_Station;

typedef struct _Message2_Station { 
    char name[128]; 
    int32_t id; 
} Message2_Station;

typedef struct _Message3_Station { 
    char name[128]; 
    int32_t id; 
} Message3_Station;

typedef struct _Message4_Station { 
    char name[128]; 
    int32_t id; 
} Message4_Station;

typedef struct _TestMessage { 
    int32_t test_number; 
} TestMessage;

typedef struct _Message1 { 
    bool has_timestamp;
    int32_t timestamp; 
    bool has_content;
    char content[128]; 
    bool has_station;
    Message1_Station station; 
} Message1;

typedef struct _Message2 { 
    bool has_timestamp;
    int32_t timestamp; 
    pb_callback_t anotherContent; 
    bool has_station;
    Message2_Station station; 
} Message2;

typedef struct _Message3 { 
    bool has_timestamp;
    int32_t timestamp; 
    bool has_stationType;
    Message3_StationType stationType; 
    bool has_station;
    Message3_Station station; 
} Message3;

typedef struct _Message4 { 
    bool has_timestamp;
    int32_t timestamp; 
    bool has_isOK;
    bool isOK; 
    bool has_station;
    Message4_Station station; 
} Message4;


/* Helper constants for enums */
#define _Message3_StationType_MIN Message3_StationType_ESP
#define _Message3_StationType_MAX Message3_StationType_RASPBERRY
#define _Message3_StationType_ARRAYSIZE ((Message3_StationType)(Message3_StationType_RASPBERRY+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TestMessage_init_default                 {0}
#define Message1_init_default                    {false, 0, false, "", false, Message1_Station_init_default}
#define Message1_Station_init_default            {"", 0}
#define Message2_init_default                    {false, 0, {{NULL}, NULL}, false, Message2_Station_init_default}
#define Message2_Station_init_default            {"", 0}
#define Message3_init_default                    {false, 0, false, _Message3_StationType_MIN, false, Message3_Station_init_default}
#define Message3_Station_init_default            {"", 0}
#define Message4_init_default                    {false, 0, false, 0, false, Message4_Station_init_default}
#define Message4_Station_init_default            {"", 0}
#define TestMessage_init_zero                    {0}
#define Message1_init_zero                       {false, 0, false, "", false, Message1_Station_init_zero}
#define Message1_Station_init_zero               {"", 0}
#define Message2_init_zero                       {false, 0, {{NULL}, NULL}, false, Message2_Station_init_zero}
#define Message2_Station_init_zero               {"", 0}
#define Message3_init_zero                       {false, 0, false, _Message3_StationType_MIN, false, Message3_Station_init_zero}
#define Message3_Station_init_zero               {"", 0}
#define Message4_init_zero                       {false, 0, false, 0, false, Message4_Station_init_zero}
#define Message4_Station_init_zero               {"", 0}

/* Field tags (for use in manual encoding/decoding) */
#define Message1_Station_name_tag                1
#define Message1_Station_id_tag                  2
#define Message2_Station_name_tag                1
#define Message2_Station_id_tag                  2
#define Message3_Station_name_tag                1
#define Message3_Station_id_tag                  2
#define Message4_Station_name_tag                1
#define Message4_Station_id_tag                  2
#define TestMessage_test_number_tag              1
#define Message1_timestamp_tag                   1
#define Message1_content_tag                     2
#define Message1_station_tag                     3
#define Message2_timestamp_tag                   1
#define Message2_anotherContent_tag              2
#define Message2_station_tag                     3
#define Message3_timestamp_tag                   1
#define Message3_stationType_tag                 2
#define Message3_station_tag                     3
#define Message4_timestamp_tag                   1
#define Message4_isOK_tag                        2
#define Message4_station_tag                     3

/* Struct field encoding specification for nanopb */
#define TestMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    test_number,       1)
#define TestMessage_CALLBACK NULL
#define TestMessage_DEFAULT NULL

#define Message1_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    timestamp,         1) \
X(a, STATIC,   OPTIONAL, STRING,   content,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  station,           3)
#define Message1_CALLBACK NULL
#define Message1_DEFAULT NULL
#define Message1_station_MSGTYPE Message1_Station

#define Message1_Station_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REQUIRED, INT32,    id,                2)
#define Message1_Station_CALLBACK NULL
#define Message1_Station_DEFAULT NULL

#define Message2_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    timestamp,         1) \
X(a, CALLBACK, REPEATED, FLOAT,    anotherContent,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  station,           3)
#define Message2_CALLBACK pb_default_field_callback
#define Message2_DEFAULT NULL
#define Message2_station_MSGTYPE Message2_Station

#define Message2_Station_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REQUIRED, INT32,    id,                2)
#define Message2_Station_CALLBACK NULL
#define Message2_Station_DEFAULT NULL

#define Message3_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    timestamp,         1) \
X(a, STATIC,   OPTIONAL, UENUM,    stationType,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  station,           3)
#define Message3_CALLBACK NULL
#define Message3_DEFAULT NULL
#define Message3_station_MSGTYPE Message3_Station

#define Message3_Station_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REQUIRED, INT32,    id,                2)
#define Message3_Station_CALLBACK NULL
#define Message3_Station_DEFAULT NULL

#define Message4_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    timestamp,         1) \
X(a, STATIC,   OPTIONAL, BOOL,     isOK,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  station,           3)
#define Message4_CALLBACK NULL
#define Message4_DEFAULT NULL
#define Message4_station_MSGTYPE Message4_Station

#define Message4_Station_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REQUIRED, INT32,    id,                2)
#define Message4_Station_CALLBACK NULL
#define Message4_Station_DEFAULT NULL

extern const pb_msgdesc_t TestMessage_msg;
extern const pb_msgdesc_t Message1_msg;
extern const pb_msgdesc_t Message1_Station_msg;
extern const pb_msgdesc_t Message2_msg;
extern const pb_msgdesc_t Message2_Station_msg;
extern const pb_msgdesc_t Message3_msg;
extern const pb_msgdesc_t Message3_Station_msg;
extern const pb_msgdesc_t Message4_msg;
extern const pb_msgdesc_t Message4_Station_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TestMessage_fields &TestMessage_msg
#define Message1_fields &Message1_msg
#define Message1_Station_fields &Message1_Station_msg
#define Message2_fields &Message2_msg
#define Message2_Station_fields &Message2_Station_msg
#define Message3_fields &Message3_msg
#define Message3_Station_fields &Message3_Station_msg
#define Message4_fields &Message4_msg
#define Message4_Station_fields &Message4_Station_msg

/* Maximum encoded size of messages (where known) */
/* Message2_size depends on runtime parameters */
#define Message1_Station_size                    141
#define Message1_size                            285
#define Message2_Station_size                    141
#define Message3_Station_size                    141
#define Message3_size                            157
#define Message4_Station_size                    141
#define Message4_size                            157
#define TestMessage_size                         11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
