/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TestMessage, TestMessage, AUTO)


PB_BIND(Message1, Message1, 2)


PB_BIND(Message1_Station, Message1_Station, AUTO)


PB_BIND(Message2, Message2, AUTO)


PB_BIND(Message2_Station, Message2_Station, AUTO)


PB_BIND(Message3, Message3, AUTO)


PB_BIND(Message3_Station, Message3_Station, AUTO)


PB_BIND(Message4, Message4, AUTO)


PB_BIND(Message4_Station, Message4_Station, AUTO)




