# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\"\n\x0bTestMessage\x12\x13\n\x0btest_number\x18\x01 \x02(\x05\"w\n\x08Message1\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\"\n\x07station\x18\x03 \x01(\x0b\x32\x11.Message1.Station\x1a#\n\x07Station\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\"~\n\x08Message2\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x16\n\x0e\x61notherContent\x18\x02 \x03(\x02\x12\"\n\x07station\x18\x03 \x01(\x0b\x32\x11.Message2.Station\x1a#\n\x07Station\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\"\xb9\x01\n\x08Message3\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12*\n\x0bstationType\x18\x02 \x01(\x0e\x32\x15.Message3.StationType\x12\"\n\x07station\x18\x03 \x01(\x0b\x32\x11.Message3.Station\x1a#\n\x07Station\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\"%\n\x0bStationType\x12\x07\n\x03\x45SP\x10\x00\x12\r\n\tRASPBERRY\x10\x01\"t\n\x08Message4\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x0c\n\x04isOK\x18\x02 \x01(\x08\x12\"\n\x07station\x18\x03 \x01(\x0b\x32\x11.Message4.Station\x1a#\n\x07Station\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTMESSAGE._serialized_start=18
  _TESTMESSAGE._serialized_end=52
  _MESSAGE1._serialized_start=54
  _MESSAGE1._serialized_end=173
  _MESSAGE1_STATION._serialized_start=138
  _MESSAGE1_STATION._serialized_end=173
  _MESSAGE2._serialized_start=175
  _MESSAGE2._serialized_end=301
  _MESSAGE2_STATION._serialized_start=138
  _MESSAGE2_STATION._serialized_end=173
  _MESSAGE3._serialized_start=304
  _MESSAGE3._serialized_end=489
  _MESSAGE3_STATION._serialized_start=138
  _MESSAGE3_STATION._serialized_end=173
  _MESSAGE3_STATIONTYPE._serialized_start=452
  _MESSAGE3_STATIONTYPE._serialized_end=489
  _MESSAGE4._serialized_start=491
  _MESSAGE4._serialized_end=607
  _MESSAGE4_STATION._serialized_start=138
  _MESSAGE4_STATION._serialized_end=173
# @@protoc_insertion_point(module_scope)
